Sprint13: ShareIt
Ekaterina1313/java-shareit pull request #1
Opened 2023-06-17 16:11 UTC by Ekaterina1313

2023-06-18 08:31 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public Booking createBooking(Booking booking) {
У тебя вот существуют классы DTO, существуют классы мапперы...
Но ничего не используется!

Контроллер должен принимать dto модели, должна быть их валидация - ее тоже нет.

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dao/BookingDao.java
> +    Booking createBooking(Booking booking);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `bookingDao.createBooking()`

Получается масло-масляное! 

Лучше: `bookingDao.create()` `bookingDao.update()`

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dao/BookingDao.java
> +    Booking getBookingById(long id);
При выборке одиночных объектов из хранилища, полезно использовать Optional.

Это поможет писать удобный код в функциональном стиле в сервисах и с него удобно начать погружение в мир функциональщины.

Optional<Booking> findById()

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dao/BookingDaoImpl.java
> +        return booking;
У тебя получается что с самого начала модель приходит с идентификатором.
А по идее идентификатор сущность будет получать только тут в хранилище.

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return bookingDao.createBooking(booking);
Что еще нужно делать в сервисе?

Например при создании, наверное хочется проверить, а нет ли уже такой же сущности...
А если есть кинуть исключение `ConflictException`

А при обновлении, нужно проверить а есть ли сущность вообще и кинуть исключение если нет `NotFoundException`

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/EmailAlreadyExistsException.java
> +public class EmailAlreadyExistsException extends RuntimeException {
Не нужно добавлять по классу на каждую сущность.
Исключения должны быть общими.
По одному для каждого кода ошибки который мы собираемся возвращать клиенту.
Например:
BadRequestException - кидаемся им, когда в процессе валидации нашли невалидное поле.
И потом обрабатываем как 400 HTTP статус код.
NotFoundException - кидаемся им, когда не нашли сущность по какому либо параметру, чаще всего по id.
Обрабатываем как 404 HTTP статус код.

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDao.java
> +    Map<Long, Item> getAllItems();
`Map<Long, Item> -> List` - отдаем как список...

Если тебе зачем-то с наружи нужна таблица, то это неверно, скорее всего нужно выставить правильный метод из `dao`

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/ItemDaoImpl.java
> +    public boolean isContainItem(long id) {
`isContainItem -> isExist`

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ValidationException("Необходимо указать id пользователя в заголовке запроса.");
Подобное это валидация. 
А валидация это зона ответственности контроллера.

2023-06-18 08:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemDao.getAllItems().values().stream()
Вот, например, тут.
Не правильно действуешь - сначала просишь все у хранилища, а потом как-то в сервисе отфильтровываешь...
Правильно будет выставить метод из хранилища и поместить этот код туда.
Ведь когда ты перейдешь на базу данных, то этот код заменится SQL запросом.

2023-06-20 04:32 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (userId == null) {
Давай нащупаем эту тонкую грань...
Смотри, вот это - это мы проверяем входные данные на адекватность

```
        if (userId == null) {
            throw new BadRequestException("Необходимо указать id пользователя в заголовке запроса.");
        }
        if (bookingDto.getEnd().isBefore(bookingDto.getStart())) {
            throw new BadRequestException("Время окончания бронирования не может быть раньше времени начала бронирования.");
        }
        if (bookingDto.getStart().isBefore(LocalDateTime.now())) {
            throw new BadRequestException("Время начала бронирования не может быть в прошлом.");
        }
```

И этому место в контроллере, но лучше конечно или выделить в метод - ведь код повторяется и при создании и при обновлении.
Или делают отдельные классы - валидаторы. 
И/Или простые случаи покрывают аннотациями для валидации, например: @Positive, @NotEmpty

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!bookingService.isContainItem(bookingDto.getItemId())) {
А вот тут мы уже сходили в базу и поняли что чего-то нет!
И это нормальная ситуация, но это уже не валидация.

Это не нужно делать в контроллере - это в сервис. 
Это его работа, он имея связь с хранилищем, в процессе своей работы понял что чего-то нет и кидаем оттуда исключение.

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dao/BookingDaoImpl.java
> +        return booking;
Отмечай, пожалуйста, комментарии как разобранные/решенные.
Можешь комментировать прям тут, задавать вопросы...

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private LocalDateTime end;
Вот `Dto` модели обычно и содержат аннотации валидации, для упрощения в простых ситуациях.

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Optional<BookingDto> getById(Long id);
Сервис `Optional` не возвращает, по причине того что в нем уже известно есть объект или нет.
Если нет то кинули исключение.

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking createdBooking = BookingMapper.fromBookingDto(bookingDto);
У тебя же есть какие-то классы мапперы - почему этот код тут?

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!Objects.equals(bookingDao.getById(id).get().getBooker().getId(), id)) {
Туту не верно - давай поясню...

Смотрим сюда: `bookingDao.getById(id).get()` - мы не можем сразу брать get() поскольку там объекта может не быть и будет `null`.

Сначала у нас есть что? Вот это `optionalBooking`

```
Optional<Booking> optionalBooking = bookingDao.getById(id);
```

И тут нам нужна проверка прежде чем достать значение, как то так например.

```
        Booking booking;
        if (optionalBooking.isPresent()) {
            booking = optionalBooking.get();
        }
```

Но это чертовски не удобно! А программисты люди ленивые! ))
Поэтому понапридумывали себе всякого, например метод: `orElseThrow`

```
        Booking foundBooking = bookingDao.getById(id)
                                         .orElseThrow(() -> new BadRequestException("Не найдена вещь с id: " + id));
```

Пробуй теперь заиспользовать это везде...

2023-06-20 04:32 UTC, FanaticFiz commented on src/main/resources/application.yml
> +spring:
Круто, молодец!

2023-06-20 20:15 UTC, Ekaterina1313 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking createdBooking = BookingMapper.fromBookingDto(bookingDto);
объясните, пожалуйста, немного подробнее, что вы имели в виду?

2023-06-21 19:55 UTC, FanaticFiz approved these changes

2023-06-21 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking createdBooking = BookingMapper.fromBookingDto(bookingDto);
Ты можешь создать в классе-мапере - `BookingMapper` удобные тебе методы с нужными параметрами, чтобы избежать установки свойств отдельно.

Например:

```
BookingMapper.fromBookingDto(bookingDto, userById, itemById);
BookingMapper.fromBookingDto(bookingDto, userById, itemById, WAITING);
```

2023-10-14 17:32 UTC, merged